11:54:03 - executor - WARNING - _skip_updates: 358 - Updates were skipped successfully.
11:59:14 - executor - WARNING - _skip_updates: 358 - Updates were skipped successfully.
12:05:07 - executor - WARNING - _skip_updates: 358 - Updates were skipped successfully.
12:08:14 - executor - WARNING - _skip_updates: 358 - Updates were skipped successfully.
12:09:32 - executor - WARNING - _skip_updates: 358 - Updates were skipped successfully.
12:10:18 - base_events - ERROR - default_exception_handler: 1744 - Task exception was never retrieved
future: <Task finished name='Task-28' coro=<Dispatcher._process_polling_updates() done, defined at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageToDeleteNotFound('Message to delete not found')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/user/Documents/TG_bot/bot/handlers.py", line 413, in in_test
    await callback.message.delete()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/types/message.py", line 3015, in delete
    return await self.bot.delete_message(self.chat.id, self.message_id)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/bot/bot.py", line 2918, in delete_message
    return await self.request(api.Methods.DELETE_MESSAGE, payload)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/bot/base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageToDeleteNotFound: Message to delete not found
12:14:27 - executor - WARNING - _skip_updates: 358 - Updates were skipped successfully.
12:15:00 - executor - WARNING - _skip_updates: 358 - Updates were skipped successfully.
12:16:05 - executor - WARNING - _skip_updates: 358 - Updates were skipped successfully.
12:19:03 - executor - WARNING - _skip_updates: 358 - Updates were skipped successfully.
